services:
  # backend:
  #   build: .
  #   image: backend-app
  #   container_name: backend-container
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MINIO_URL=minio
  #     - MINIO_ROOT_USER=minio_access_key
  #     - MINIO_ROOT_PASSWORD=minio_secret_key
  #   depends_on:
  #     - minio

  minio:
    image: minio/minio
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
